package com.andre.sistema.domain;
// Generated 17/01/2015 12:38:08 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * T0002tipopersona generated by hbm2java
 */
@SuppressWarnings("serial")
public class T0002tipopersona  implements java.io.Serializable {


     private short i0002idtipopersona;
     private String c0002nombre;
     private String c0002usuario;
     private Date d0002fecha;
     private String c0002pc;
     private String c0002ip;
     private boolean b0002estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;
     private Set t0003subtippersonas = new HashSet(0);

    public T0002tipopersona() {
    }

	
    public T0002tipopersona(short i0002idtipopersona, String c0002nombre, String c0002usuario, Date d0002fecha, String c0002pc, String c0002ip, boolean b0002estado) {
        this.i0002idtipopersona = i0002idtipopersona;
        this.c0002nombre = c0002nombre;
        this.c0002usuario = c0002usuario;
        this.d0002fecha = d0002fecha;
        this.c0002pc = c0002pc;
        this.c0002ip = c0002ip;
        this.b0002estado = b0002estado;
    }
    public T0002tipopersona(short i0002idtipopersona, String c0002nombre, String c0002usuario, Date d0002fecha, String c0002pc, String c0002ip, boolean b0002estado, String cusuarioMod, String cobservacion, String cipMod, Set t0003subtippersonas) {
       this.i0002idtipopersona = i0002idtipopersona;
       this.c0002nombre = c0002nombre;
       this.c0002usuario = c0002usuario;
       this.d0002fecha = d0002fecha;
       this.c0002pc = c0002pc;
       this.c0002ip = c0002ip;
       this.b0002estado = b0002estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
       this.t0003subtippersonas = t0003subtippersonas;
    }
   
    public short getI0002idtipopersona() {
        return this.i0002idtipopersona;
    }
    
    public void setI0002idtipopersona(short i0002idtipopersona) {
        this.i0002idtipopersona = i0002idtipopersona;
    }
    public String getC0002nombre() {
        return this.c0002nombre;
    }
    
    public void setC0002nombre(String c0002nombre) {
        this.c0002nombre = c0002nombre;
    }
    public String getC0002usuario() {
        return this.c0002usuario;
    }
    
    public void setC0002usuario(String c0002usuario) {
        this.c0002usuario = c0002usuario;
    }
    public Date getD0002fecha() {
        return this.d0002fecha;
    }
    
    public void setD0002fecha(Date d0002fecha) {
        this.d0002fecha = d0002fecha;
    }
    public String getC0002pc() {
        return this.c0002pc;
    }
    
    public void setC0002pc(String c0002pc) {
        this.c0002pc = c0002pc;
    }
    public String getC0002ip() {
        return this.c0002ip;
    }
    
    public void setC0002ip(String c0002ip) {
        this.c0002ip = c0002ip;
    }
    public boolean isB0002estado() {
        return this.b0002estado;
    }
    
    public void setB0002estado(boolean b0002estado) {
        this.b0002estado = b0002estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }
    public Set getT0003subtippersonas() {
        return this.t0003subtippersonas;
    }
    
    public void setT0003subtippersonas(Set t0003subtippersonas) {
        this.t0003subtippersonas = t0003subtippersonas;
    }




}


