package com.andre.sistema.domain;
// Generated 17/01/2015 12:38:08 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * T0006paises generated by hbm2java
 */
@SuppressWarnings("serial")
public class T0006paises  implements java.io.Serializable {


     private int i0006idpais;
     private String c0006nombre;
     private String c0006gentilicio;
     private String c0006usuario;
     private Date d0006fecha;
     private String c0006pc;
     private String c0006ip;
     private boolean b0006estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;
     private Set t0001personases = new HashSet(0);

    public T0006paises() {
    }

	
    public T0006paises(int i0006idpais, String c0006nombre, String c0006gentilicio, String c0006usuario, Date d0006fecha, String c0006pc, String c0006ip, boolean b0006estado) {
        this.i0006idpais = i0006idpais;
        this.c0006nombre = c0006nombre;
        this.c0006gentilicio = c0006gentilicio;
        this.c0006usuario = c0006usuario;
        this.d0006fecha = d0006fecha;
        this.c0006pc = c0006pc;
        this.c0006ip = c0006ip;
        this.b0006estado = b0006estado;
    }
    public T0006paises(int i0006idpais, String c0006nombre, String c0006gentilicio, String c0006usuario, Date d0006fecha, String c0006pc, String c0006ip, boolean b0006estado, String cusuarioMod, String cobservacion, String cipMod, Set t0001personases) {
       this.i0006idpais = i0006idpais;
       this.c0006nombre = c0006nombre;
       this.c0006gentilicio = c0006gentilicio;
       this.c0006usuario = c0006usuario;
       this.d0006fecha = d0006fecha;
       this.c0006pc = c0006pc;
       this.c0006ip = c0006ip;
       this.b0006estado = b0006estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
       this.t0001personases = t0001personases;
    }
   
    public int getI0006idpais() {
        return this.i0006idpais;
    }
    
    public void setI0006idpais(int i0006idpais) {
        this.i0006idpais = i0006idpais;
    }
    public String getC0006nombre() {
        return this.c0006nombre;
    }
    
    public void setC0006nombre(String c0006nombre) {
        this.c0006nombre = c0006nombre;
    }
    public String getC0006gentilicio() {
        return this.c0006gentilicio;
    }
    
    public void setC0006gentilicio(String c0006gentilicio) {
        this.c0006gentilicio = c0006gentilicio;
    }
    public String getC0006usuario() {
        return this.c0006usuario;
    }
    
    public void setC0006usuario(String c0006usuario) {
        this.c0006usuario = c0006usuario;
    }
    public Date getD0006fecha() {
        return this.d0006fecha;
    }
    
    public void setD0006fecha(Date d0006fecha) {
        this.d0006fecha = d0006fecha;
    }
    public String getC0006pc() {
        return this.c0006pc;
    }
    
    public void setC0006pc(String c0006pc) {
        this.c0006pc = c0006pc;
    }
    public String getC0006ip() {
        return this.c0006ip;
    }
    
    public void setC0006ip(String c0006ip) {
        this.c0006ip = c0006ip;
    }
    public boolean isB0006estado() {
        return this.b0006estado;
    }
    
    public void setB0006estado(boolean b0006estado) {
        this.b0006estado = b0006estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }
    public Set getT0001personases() {
        return this.t0001personases;
    }
    
    public void setT0001personases(Set t0001personases) {
        this.t0001personases = t0001personases;
    }




}


