package com.andre.sistema.domain;
// Generated 17/01/2015 12:38:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * T0001personas generated by hbm2java
 */
@SuppressWarnings("serial")
public class T0001personas  implements java.io.Serializable {


     private String c0001codpersona;
     private T0003subtippersona t0003subtippersona;
     private T0006paises t0006paises;
     private boolean b0001contribuyente;
     private String c0001nombre;
     private String c0001idlugar;
     private String c0001codvia;
     private String c0001numero;
     private String c0001dpto;
     private String c0001piso;
     private String c0001block;
     private String c0001manzana;
     private String c0001lote;
     private String c0001usuario;
     private Date d0001fecha;
     private String c0001pc;
     private String c0001ip;
     private boolean b0001estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;

    public T0001personas() {
    }

	
    public T0001personas(String c0001codpersona, T0003subtippersona t0003subtippersona, T0006paises t0006paises, boolean b0001contribuyente, String c0001nombre, String c0001idlugar, String c0001codvia, String c0001usuario, Date d0001fecha, String c0001pc, String c0001ip, boolean b0001estado) {
        this.c0001codpersona = c0001codpersona;
        this.t0003subtippersona = t0003subtippersona;
        this.t0006paises = t0006paises;
        this.b0001contribuyente = b0001contribuyente;
        this.c0001nombre = c0001nombre;
        this.c0001idlugar = c0001idlugar;
        this.c0001codvia = c0001codvia;
        this.c0001usuario = c0001usuario;
        this.d0001fecha = d0001fecha;
        this.c0001pc = c0001pc;
        this.c0001ip = c0001ip;
        this.b0001estado = b0001estado;
    }
    public T0001personas(String c0001codpersona, T0003subtippersona t0003subtippersona, T0006paises t0006paises, boolean b0001contribuyente, String c0001nombre, String c0001idlugar, String c0001codvia, String c0001numero, String c0001dpto, String c0001piso, String c0001block, String c0001manzana, String c0001lote, String c0001usuario, Date d0001fecha, String c0001pc, String c0001ip, boolean b0001estado, String cusuarioMod, String cobservacion, String cipMod) {
       this.c0001codpersona = c0001codpersona;
       this.t0003subtippersona = t0003subtippersona;
       this.t0006paises = t0006paises;
       this.b0001contribuyente = b0001contribuyente;
       this.c0001nombre = c0001nombre;
       this.c0001idlugar = c0001idlugar;
       this.c0001codvia = c0001codvia;
       this.c0001numero = c0001numero;
       this.c0001dpto = c0001dpto;
       this.c0001piso = c0001piso;
       this.c0001block = c0001block;
       this.c0001manzana = c0001manzana;
       this.c0001lote = c0001lote;
       this.c0001usuario = c0001usuario;
       this.d0001fecha = d0001fecha;
       this.c0001pc = c0001pc;
       this.c0001ip = c0001ip;
       this.b0001estado = b0001estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
    }
   
    public String getC0001codpersona() {
        return this.c0001codpersona;
    }
    
    public void setC0001codpersona(String c0001codpersona) {
        this.c0001codpersona = c0001codpersona;
    }
    public T0003subtippersona getT0003subtippersona() {
        return this.t0003subtippersona;
    }
    
    public void setT0003subtippersona(T0003subtippersona t0003subtippersona) {
        this.t0003subtippersona = t0003subtippersona;
    }
    public T0006paises getT0006paises() {
        return this.t0006paises;
    }
    
    public void setT0006paises(T0006paises t0006paises) {
        this.t0006paises = t0006paises;
    }
    public boolean isB0001contribuyente() {
        return this.b0001contribuyente;
    }
    
    public void setB0001contribuyente(boolean b0001contribuyente) {
        this.b0001contribuyente = b0001contribuyente;
    }
    public String getC0001nombre() {
        return this.c0001nombre;
    }
    
    public void setC0001nombre(String c0001nombre) {
        this.c0001nombre = c0001nombre;
    }
    public String getC0001idlugar() {
        return this.c0001idlugar;
    }
    
    public void setC0001idlugar(String c0001idlugar) {
        this.c0001idlugar = c0001idlugar;
    }
    public String getC0001codvia() {
        return this.c0001codvia;
    }
    
    public void setC0001codvia(String c0001codvia) {
        this.c0001codvia = c0001codvia;
    }
    public String getC0001numero() {
        return this.c0001numero;
    }
    
    public void setC0001numero(String c0001numero) {
        this.c0001numero = c0001numero;
    }
    public String getC0001dpto() {
        return this.c0001dpto;
    }
    
    public void setC0001dpto(String c0001dpto) {
        this.c0001dpto = c0001dpto;
    }
    public String getC0001piso() {
        return this.c0001piso;
    }
    
    public void setC0001piso(String c0001piso) {
        this.c0001piso = c0001piso;
    }
    public String getC0001block() {
        return this.c0001block;
    }
    
    public void setC0001block(String c0001block) {
        this.c0001block = c0001block;
    }
    public String getC0001manzana() {
        return this.c0001manzana;
    }
    
    public void setC0001manzana(String c0001manzana) {
        this.c0001manzana = c0001manzana;
    }
    public String getC0001lote() {
        return this.c0001lote;
    }
    
    public void setC0001lote(String c0001lote) {
        this.c0001lote = c0001lote;
    }
    public String getC0001usuario() {
        return this.c0001usuario;
    }
    
    public void setC0001usuario(String c0001usuario) {
        this.c0001usuario = c0001usuario;
    }
    public Date getD0001fecha() {
        return this.d0001fecha;
    }
    
    public void setD0001fecha(Date d0001fecha) {
        this.d0001fecha = d0001fecha;
    }
    public String getC0001pc() {
        return this.c0001pc;
    }
    
    public void setC0001pc(String c0001pc) {
        this.c0001pc = c0001pc;
    }
    public String getC0001ip() {
        return this.c0001ip;
    }
    
    public void setC0001ip(String c0001ip) {
        this.c0001ip = c0001ip;
    }
    public boolean isB0001estado() {
        return this.b0001estado;
    }
    
    public void setB0001estado(boolean b0001estado) {
        this.b0001estado = b0001estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }




}


