package com.andre.sistema.domain;
// Generated 28/01/2015 11:17:22 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * T0008lugares generated by hbm2java
 */
public class T0008lugares  implements java.io.Serializable {


     private String c0008idlugar;
     private T0011tipolugar t0011tipolugar;
     private String c0008nombre;
     private short i0008idsocecon;
     private short i0008idubigeo;
     private String c0008usuario;
     private Date d0008fecha;
     private String c0008pc;
     private String c0008ip;
     private boolean b0008estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;
     private Set t0017personasdomicilioses = new HashSet(0);

    public T0008lugares() {
    }

	
    public T0008lugares(String c0008idlugar, T0011tipolugar t0011tipolugar, String c0008nombre, short i0008idsocecon, short i0008idubigeo, String c0008usuario, Date d0008fecha, String c0008pc, String c0008ip, boolean b0008estado) {
        this.c0008idlugar = c0008idlugar;
        this.t0011tipolugar = t0011tipolugar;
        this.c0008nombre = c0008nombre;
        this.i0008idsocecon = i0008idsocecon;
        this.i0008idubigeo = i0008idubigeo;
        this.c0008usuario = c0008usuario;
        this.d0008fecha = d0008fecha;
        this.c0008pc = c0008pc;
        this.c0008ip = c0008ip;
        this.b0008estado = b0008estado;
    }
    public T0008lugares(String c0008idlugar, T0011tipolugar t0011tipolugar, String c0008nombre, short i0008idsocecon, short i0008idubigeo, String c0008usuario, Date d0008fecha, String c0008pc, String c0008ip, boolean b0008estado, String cusuarioMod, String cobservacion, String cipMod, Set t0017personasdomicilioses) {
       this.c0008idlugar = c0008idlugar;
       this.t0011tipolugar = t0011tipolugar;
       this.c0008nombre = c0008nombre;
       this.i0008idsocecon = i0008idsocecon;
       this.i0008idubigeo = i0008idubigeo;
       this.c0008usuario = c0008usuario;
       this.d0008fecha = d0008fecha;
       this.c0008pc = c0008pc;
       this.c0008ip = c0008ip;
       this.b0008estado = b0008estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
       this.t0017personasdomicilioses = t0017personasdomicilioses;
    }
   
    public String getC0008idlugar() {
        return this.c0008idlugar;
    }
    
    public void setC0008idlugar(String c0008idlugar) {
        this.c0008idlugar = c0008idlugar;
    }
    public T0011tipolugar getT0011tipolugar() {
        return this.t0011tipolugar;
    }
    
    public void setT0011tipolugar(T0011tipolugar t0011tipolugar) {
        this.t0011tipolugar = t0011tipolugar;
    }
    public String getC0008nombre() {
        return this.c0008nombre;
    }
    
    public void setC0008nombre(String c0008nombre) {
        this.c0008nombre = c0008nombre;
    }
    public short getI0008idsocecon() {
        return this.i0008idsocecon;
    }
    
    public void setI0008idsocecon(short i0008idsocecon) {
        this.i0008idsocecon = i0008idsocecon;
    }
    public short getI0008idubigeo() {
        return this.i0008idubigeo;
    }
    
    public void setI0008idubigeo(short i0008idubigeo) {
        this.i0008idubigeo = i0008idubigeo;
    }
    public String getC0008usuario() {
        return this.c0008usuario;
    }
    
    public void setC0008usuario(String c0008usuario) {
        this.c0008usuario = c0008usuario;
    }
    public Date getD0008fecha() {
        return this.d0008fecha;
    }
    
    public void setD0008fecha(Date d0008fecha) {
        this.d0008fecha = d0008fecha;
    }
    public String getC0008pc() {
        return this.c0008pc;
    }
    
    public void setC0008pc(String c0008pc) {
        this.c0008pc = c0008pc;
    }
    public String getC0008ip() {
        return this.c0008ip;
    }
    
    public void setC0008ip(String c0008ip) {
        this.c0008ip = c0008ip;
    }
    public boolean isB0008estado() {
        return this.b0008estado;
    }
    
    public void setB0008estado(boolean b0008estado) {
        this.b0008estado = b0008estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }
    public Set getT0017personasdomicilioses() {
        return this.t0017personasdomicilioses;
    }
    
    public void setT0017personasdomicilioses(Set t0017personasdomicilioses) {
        this.t0017personasdomicilioses = t0017personasdomicilioses;
    }




}


