package com.andre.sistema.domain;
// Generated 28/01/2015 11:17:22 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * T0012vias generated by hbm2java
 */
public class T0012vias  implements java.io.Serializable {


     private String c0012codvia;
     private String c0012nombre;
     private short i0012idtipovia;
     private String c0012usuario;
     private Date d0012fecha;
     private String c0012pc;
     private String c0012ip;
     private boolean b0012estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;
     private Set t0017personasdomicilioses = new HashSet(0);

    public T0012vias() {
    }

	
    public T0012vias(String c0012codvia, String c0012nombre, short i0012idtipovia, String c0012usuario, Date d0012fecha, String c0012pc, String c0012ip, boolean b0012estado) {
        this.c0012codvia = c0012codvia;
        this.c0012nombre = c0012nombre;
        this.i0012idtipovia = i0012idtipovia;
        this.c0012usuario = c0012usuario;
        this.d0012fecha = d0012fecha;
        this.c0012pc = c0012pc;
        this.c0012ip = c0012ip;
        this.b0012estado = b0012estado;
    }
    public T0012vias(String c0012codvia, String c0012nombre, short i0012idtipovia, String c0012usuario, Date d0012fecha, String c0012pc, String c0012ip, boolean b0012estado, String cusuarioMod, String cobservacion, String cipMod, Set t0017personasdomicilioses) {
       this.c0012codvia = c0012codvia;
       this.c0012nombre = c0012nombre;
       this.i0012idtipovia = i0012idtipovia;
       this.c0012usuario = c0012usuario;
       this.d0012fecha = d0012fecha;
       this.c0012pc = c0012pc;
       this.c0012ip = c0012ip;
       this.b0012estado = b0012estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
       this.t0017personasdomicilioses = t0017personasdomicilioses;
    }
   
    public String getC0012codvia() {
        return this.c0012codvia;
    }
    
    public void setC0012codvia(String c0012codvia) {
        this.c0012codvia = c0012codvia;
    }
    public String getC0012nombre() {
        return this.c0012nombre;
    }
    
    public void setC0012nombre(String c0012nombre) {
        this.c0012nombre = c0012nombre;
    }
    public short getI0012idtipovia() {
        return this.i0012idtipovia;
    }
    
    public void setI0012idtipovia(short i0012idtipovia) {
        this.i0012idtipovia = i0012idtipovia;
    }
    public String getC0012usuario() {
        return this.c0012usuario;
    }
    
    public void setC0012usuario(String c0012usuario) {
        this.c0012usuario = c0012usuario;
    }
    public Date getD0012fecha() {
        return this.d0012fecha;
    }
    
    public void setD0012fecha(Date d0012fecha) {
        this.d0012fecha = d0012fecha;
    }
    public String getC0012pc() {
        return this.c0012pc;
    }
    
    public void setC0012pc(String c0012pc) {
        this.c0012pc = c0012pc;
    }
    public String getC0012ip() {
        return this.c0012ip;
    }
    
    public void setC0012ip(String c0012ip) {
        this.c0012ip = c0012ip;
    }
    public boolean isB0012estado() {
        return this.b0012estado;
    }
    
    public void setB0012estado(boolean b0012estado) {
        this.b0012estado = b0012estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }
    public Set getT0017personasdomicilioses() {
        return this.t0017personasdomicilioses;
    }
    
    public void setT0017personasdomicilioses(Set t0017personasdomicilioses) {
        this.t0017personasdomicilioses = t0017personasdomicilioses;
    }




}


