package com.andre.sistema.domain;
// Generated 28/01/2015 11:17:22 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * T0011tipolugar generated by hbm2java
 */
public class T0011tipolugar  implements java.io.Serializable {


     private short i0011idtiplugar;
     private String c0011nombre;
     private String c0011abrev;
     private String c0011usuario;
     private Date d0011fecha;
     private String c0011pc;
     private String c0011ip;
     private boolean b0011estado;
     private String cusuarioMod;
     private String cobservacion;
     private String cipMod;
     private Set t0008lugareses = new HashSet(0);

    public T0011tipolugar() {
    }

	
    public T0011tipolugar(short i0011idtiplugar, String c0011nombre, String c0011abrev, String c0011usuario, Date d0011fecha, String c0011pc, String c0011ip, boolean b0011estado) {
        this.i0011idtiplugar = i0011idtiplugar;
        this.c0011nombre = c0011nombre;
        this.c0011abrev = c0011abrev;
        this.c0011usuario = c0011usuario;
        this.d0011fecha = d0011fecha;
        this.c0011pc = c0011pc;
        this.c0011ip = c0011ip;
        this.b0011estado = b0011estado;
    }
    public T0011tipolugar(short i0011idtiplugar, String c0011nombre, String c0011abrev, String c0011usuario, Date d0011fecha, String c0011pc, String c0011ip, boolean b0011estado, String cusuarioMod, String cobservacion, String cipMod, Set t0008lugareses) {
       this.i0011idtiplugar = i0011idtiplugar;
       this.c0011nombre = c0011nombre;
       this.c0011abrev = c0011abrev;
       this.c0011usuario = c0011usuario;
       this.d0011fecha = d0011fecha;
       this.c0011pc = c0011pc;
       this.c0011ip = c0011ip;
       this.b0011estado = b0011estado;
       this.cusuarioMod = cusuarioMod;
       this.cobservacion = cobservacion;
       this.cipMod = cipMod;
       this.t0008lugareses = t0008lugareses;
    }
   
    public short getI0011idtiplugar() {
        return this.i0011idtiplugar;
    }
    
    public void setI0011idtiplugar(short i0011idtiplugar) {
        this.i0011idtiplugar = i0011idtiplugar;
    }
    public String getC0011nombre() {
        return this.c0011nombre;
    }
    
    public void setC0011nombre(String c0011nombre) {
        this.c0011nombre = c0011nombre;
    }
    public String getC0011abrev() {
        return this.c0011abrev;
    }
    
    public void setC0011abrev(String c0011abrev) {
        this.c0011abrev = c0011abrev;
    }
    public String getC0011usuario() {
        return this.c0011usuario;
    }
    
    public void setC0011usuario(String c0011usuario) {
        this.c0011usuario = c0011usuario;
    }
    public Date getD0011fecha() {
        return this.d0011fecha;
    }
    
    public void setD0011fecha(Date d0011fecha) {
        this.d0011fecha = d0011fecha;
    }
    public String getC0011pc() {
        return this.c0011pc;
    }
    
    public void setC0011pc(String c0011pc) {
        this.c0011pc = c0011pc;
    }
    public String getC0011ip() {
        return this.c0011ip;
    }
    
    public void setC0011ip(String c0011ip) {
        this.c0011ip = c0011ip;
    }
    public boolean isB0011estado() {
        return this.b0011estado;
    }
    
    public void setB0011estado(boolean b0011estado) {
        this.b0011estado = b0011estado;
    }
    public String getCusuarioMod() {
        return this.cusuarioMod;
    }
    
    public void setCusuarioMod(String cusuarioMod) {
        this.cusuarioMod = cusuarioMod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipMod() {
        return this.cipMod;
    }
    
    public void setCipMod(String cipMod) {
        this.cipMod = cipMod;
    }
    public Set getT0008lugareses() {
        return this.t0008lugareses;
    }
    
    public void setT0008lugareses(Set t0008lugareses) {
        this.t0008lugareses = t0008lugareses;
    }




}


