package com.andre.sistema.domain;
// Generated 28/01/2015 11:17:22 AM by Hibernate Tools 3.6.0



/**
 * T0017personasdomiciliosId generated by hbm2java
 */
public class T0017personasdomiciliosId  implements java.io.Serializable {


     private String c0017codpersona;
     private String c0017codvia;
     private String c0017idlugar;
     private boolean b0017tipodomicilio;
     private String c0017numero;
     private String c0017manzana;
     private String c0017lote;

    public T0017personasdomiciliosId() {
    }

    public T0017personasdomiciliosId(String c0017codpersona, String c0017codvia, String c0017idlugar, boolean b0017tipodomicilio, String c0017numero, String c0017manzana, String c0017lote) {
       this.c0017codpersona = c0017codpersona;
       this.c0017codvia = c0017codvia;
       this.c0017idlugar = c0017idlugar;
       this.b0017tipodomicilio = b0017tipodomicilio;
       this.c0017numero = c0017numero;
       this.c0017manzana = c0017manzana;
       this.c0017lote = c0017lote;
    }
   
    public String getC0017codpersona() {
        return this.c0017codpersona;
    }
    
    public void setC0017codpersona(String c0017codpersona) {
        this.c0017codpersona = c0017codpersona;
    }
    public String getC0017codvia() {
        return this.c0017codvia;
    }
    
    public void setC0017codvia(String c0017codvia) {
        this.c0017codvia = c0017codvia;
    }
    public String getC0017idlugar() {
        return this.c0017idlugar;
    }
    
    public void setC0017idlugar(String c0017idlugar) {
        this.c0017idlugar = c0017idlugar;
    }
    public boolean isB0017tipodomicilio() {
        return this.b0017tipodomicilio;
    }
    
    public void setB0017tipodomicilio(boolean b0017tipodomicilio) {
        this.b0017tipodomicilio = b0017tipodomicilio;
    }
    public String getC0017numero() {
        return this.c0017numero;
    }
    
    public void setC0017numero(String c0017numero) {
        this.c0017numero = c0017numero;
    }
    public String getC0017manzana() {
        return this.c0017manzana;
    }
    
    public void setC0017manzana(String c0017manzana) {
        this.c0017manzana = c0017manzana;
    }
    public String getC0017lote() {
        return this.c0017lote;
    }
    
    public void setC0017lote(String c0017lote) {
        this.c0017lote = c0017lote;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof T0017personasdomiciliosId) ) return false;
		 T0017personasdomiciliosId castOther = ( T0017personasdomiciliosId ) other; 
         
		 return ( (this.getC0017codpersona()==castOther.getC0017codpersona()) || ( this.getC0017codpersona()!=null && castOther.getC0017codpersona()!=null && this.getC0017codpersona().equals(castOther.getC0017codpersona()) ) )
 && ( (this.getC0017codvia()==castOther.getC0017codvia()) || ( this.getC0017codvia()!=null && castOther.getC0017codvia()!=null && this.getC0017codvia().equals(castOther.getC0017codvia()) ) )
 && ( (this.getC0017idlugar()==castOther.getC0017idlugar()) || ( this.getC0017idlugar()!=null && castOther.getC0017idlugar()!=null && this.getC0017idlugar().equals(castOther.getC0017idlugar()) ) )
 && (this.isB0017tipodomicilio()==castOther.isB0017tipodomicilio())
 && ( (this.getC0017numero()==castOther.getC0017numero()) || ( this.getC0017numero()!=null && castOther.getC0017numero()!=null && this.getC0017numero().equals(castOther.getC0017numero()) ) )
 && ( (this.getC0017manzana()==castOther.getC0017manzana()) || ( this.getC0017manzana()!=null && castOther.getC0017manzana()!=null && this.getC0017manzana().equals(castOther.getC0017manzana()) ) )
 && ( (this.getC0017lote()==castOther.getC0017lote()) || ( this.getC0017lote()!=null && castOther.getC0017lote()!=null && this.getC0017lote().equals(castOther.getC0017lote()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getC0017codpersona() == null ? 0 : this.getC0017codpersona().hashCode() );
         result = 37 * result + ( getC0017codvia() == null ? 0 : this.getC0017codvia().hashCode() );
         result = 37 * result + ( getC0017idlugar() == null ? 0 : this.getC0017idlugar().hashCode() );
         result = 37 * result + (this.isB0017tipodomicilio()?1:0);
         result = 37 * result + ( getC0017numero() == null ? 0 : this.getC0017numero().hashCode() );
         result = 37 * result + ( getC0017manzana() == null ? 0 : this.getC0017manzana().hashCode() );
         result = 37 * result + ( getC0017lote() == null ? 0 : this.getC0017lote().hashCode() );
         return result;
   }   


}


