package com.andre.sistema.domain;
// Generated 28/01/2015 11:17:22 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * T0017personasdomicilios generated by hbm2java
 */
public class T0017personasdomicilios  implements java.io.Serializable {


     private T0017personasdomiciliosId id;
     private T0001personas t0001personas;
     private T0008lugares t0008lugares;
     private T0012vias t0012vias;
     private String c0017dpto;
     private String c0017piso;
     private String c0017block;
     private String c0017usuario;
     private Date d0017fecha;
     private String c0017pc;
     private String c0017ip;
     private boolean b0017estado;
     private String cusuariomod;
     private String cobservacion;
     private String cipmod;
     private String c0017sublote;
     private String c0017edificacion;
     private String c0017sector;

    public T0017personasdomicilios() {
    }

	
    public T0017personasdomicilios(T0017personasdomiciliosId id, T0001personas t0001personas, T0008lugares t0008lugares, T0012vias t0012vias, String c0017usuario, Date d0017fecha, String c0017pc, String c0017ip, boolean b0017estado) {
        this.id = id;
        this.t0001personas = t0001personas;
        this.t0008lugares = t0008lugares;
        this.t0012vias = t0012vias;
        this.c0017usuario = c0017usuario;
        this.d0017fecha = d0017fecha;
        this.c0017pc = c0017pc;
        this.c0017ip = c0017ip;
        this.b0017estado = b0017estado;
    }
    public T0017personasdomicilios(T0017personasdomiciliosId id, T0001personas t0001personas, T0008lugares t0008lugares, T0012vias t0012vias, String c0017dpto, String c0017piso, String c0017block, String c0017usuario, Date d0017fecha, String c0017pc, String c0017ip, boolean b0017estado, String cusuariomod, String cobservacion, String cipmod, String c0017sublote, String c0017edificacion, String c0017sector) {
       this.id = id;
       this.t0001personas = t0001personas;
       this.t0008lugares = t0008lugares;
       this.t0012vias = t0012vias;
       this.c0017dpto = c0017dpto;
       this.c0017piso = c0017piso;
       this.c0017block = c0017block;
       this.c0017usuario = c0017usuario;
       this.d0017fecha = d0017fecha;
       this.c0017pc = c0017pc;
       this.c0017ip = c0017ip;
       this.b0017estado = b0017estado;
       this.cusuariomod = cusuariomod;
       this.cobservacion = cobservacion;
       this.cipmod = cipmod;
       this.c0017sublote = c0017sublote;
       this.c0017edificacion = c0017edificacion;
       this.c0017sector = c0017sector;
    }
   
    public T0017personasdomiciliosId getId() {
        return this.id;
    }
    
    public void setId(T0017personasdomiciliosId id) {
        this.id = id;
    }
    public T0001personas getT0001personas() {
        return this.t0001personas;
    }
    
    public void setT0001personas(T0001personas t0001personas) {
        this.t0001personas = t0001personas;
    }
    public T0008lugares getT0008lugares() {
        return this.t0008lugares;
    }
    
    public void setT0008lugares(T0008lugares t0008lugares) {
        this.t0008lugares = t0008lugares;
    }
    public T0012vias getT0012vias() {
        return this.t0012vias;
    }
    
    public void setT0012vias(T0012vias t0012vias) {
        this.t0012vias = t0012vias;
    }
    public String getC0017dpto() {
        return this.c0017dpto;
    }
    
    public void setC0017dpto(String c0017dpto) {
        this.c0017dpto = c0017dpto;
    }
    public String getC0017piso() {
        return this.c0017piso;
    }
    
    public void setC0017piso(String c0017piso) {
        this.c0017piso = c0017piso;
    }
    public String getC0017block() {
        return this.c0017block;
    }
    
    public void setC0017block(String c0017block) {
        this.c0017block = c0017block;
    }
    public String getC0017usuario() {
        return this.c0017usuario;
    }
    
    public void setC0017usuario(String c0017usuario) {
        this.c0017usuario = c0017usuario;
    }
    public Date getD0017fecha() {
        return this.d0017fecha;
    }
    
    public void setD0017fecha(Date d0017fecha) {
        this.d0017fecha = d0017fecha;
    }
    public String getC0017pc() {
        return this.c0017pc;
    }
    
    public void setC0017pc(String c0017pc) {
        this.c0017pc = c0017pc;
    }
    public String getC0017ip() {
        return this.c0017ip;
    }
    
    public void setC0017ip(String c0017ip) {
        this.c0017ip = c0017ip;
    }
    public boolean isB0017estado() {
        return this.b0017estado;
    }
    
    public void setB0017estado(boolean b0017estado) {
        this.b0017estado = b0017estado;
    }
    public String getCusuariomod() {
        return this.cusuariomod;
    }
    
    public void setCusuariomod(String cusuariomod) {
        this.cusuariomod = cusuariomod;
    }
    public String getCobservacion() {
        return this.cobservacion;
    }
    
    public void setCobservacion(String cobservacion) {
        this.cobservacion = cobservacion;
    }
    public String getCipmod() {
        return this.cipmod;
    }
    
    public void setCipmod(String cipmod) {
        this.cipmod = cipmod;
    }
    public String getC0017sublote() {
        return this.c0017sublote;
    }
    
    public void setC0017sublote(String c0017sublote) {
        this.c0017sublote = c0017sublote;
    }
    public String getC0017edificacion() {
        return this.c0017edificacion;
    }
    
    public void setC0017edificacion(String c0017edificacion) {
        this.c0017edificacion = c0017edificacion;
    }
    public String getC0017sector() {
        return this.c0017sector;
    }
    
    public void setC0017sector(String c0017sector) {
        this.c0017sector = c0017sector;
    }




}


